---
# Slurm config bwuni gpu
name: "SLURM"   # MUST BE "SLURM"
partition: "gpu"  # "single" for cpu, "gpu_4" or gpu_8" for gpu
job-name: "robot_push_promp" # this will be the experiment's name in slurm
num_parallel_jobs: 20  # max number of jobs executed in parallel
ntasks: 1   #  leave that like it is
cpus-per-task: 2   # there are 10 cores for each GPU
mem-per-cpu: 10000  # in MB
time: 1000   # in minutes
sbatch_args: # gpus need to be explicitly requested using this
  gres=gpu:1: ""   #and this



---
name: &name robot_push_promp

# Required: Can also be set in DEFAULT
path: /tmp/result/robot_push_promp   # path for saving the results
repetitions: 1    # number of repeated runs for each parameter combination

# Required for AbstractIterativeExperiments only. Can also be set in DEFAULT
iterations: 10000  # number of iterations per repetition.

# Optional: Can also be set in DEFAULT
# Only change these values if you are sure you know what you are doing.
reps_per_job: 1    # number of repetitions in each job. useful for paralellization. defaults to 1.
reps_in_parallel: 20

wandb:
  project: robot_push_promp
  group: *name
  entity: gelikit
  log_interval:  &interval 20
  log_model: true
  model_name: model


params:
  dim_lat: &dim_lat 128
  act_func: &act_func leaky_relu
  lr: 2e-4
  wd: 5e-5
  vali_log_interval: *interval
  save_model_interval: 500
  seed: 1234
  max_norm: 150

  encoders:
    ctx:
      type: ProNMPEncoderMlp
      args:
        dim_obs: 8
        dim_lat: *dim_lat
        obs_hidden:
          avg_neuron: 128
          num_hidden: 3
          shape: 0.0
        unc_hidden:
          avg_neuron: 128
          num_hidden: 3
          shape: 0.0
        act_func: *act_func

  aggregator:
    type: BayesianAggregator
    args:
      dim_lat: *dim_lat
      multiple_steps: false
      prior_mean: 0.0
      prior_var: 1

  decoder:
    type: PBDecoder
    args:
      dim_add_in: 0
      dim_val: 20
      dim_lat: *dim_lat
      std_only: false
      mean_hidden:
        avg_neuron: 128
        num_hidden: 3
        shape: 0.0
      variance_hidden:
        avg_neuron: 128
        num_hidden: 3
        shape: 0.0
      act_func: *act_func

  dataset:
    name: robot_push
    partition:
      train: 0.7
      validate: 0.2
      test: 0.1
    shuffle_set: True
    batch_size: 48
    shuffle_train_loader: True
    transform: null
    time_min: 0
    time_max: 3
    save_type: tensor
    data:
      object_pos_ori:
        time_dependent: true
      des_cart_pos_vel:
        time_dependent: true
      box_robot_state:
        time_dependent: true
      file_index:
        time_dependent: false
        normalize: false

  mp:
    num_dof: 2
    tau: 0.5
    mp_type: promp
    mp_args:
      num_basis: 10
      basis_bandwidth_factor: 3
      num_basis_outside: 0
      dt: 0.01

  assign_config:
    num_ctx_min: 1
    num_ctx_max: 10
    pred_range_min: 50
    pred_range_max: 50

